### ISSUE TITLE
gammu connection problem - device no permission

### ISSUE THREAD

**Issue by Biegnik** [infrat/mqtt2sms-addon#9]
Hi,
I cant connect to modem:
Thu 2024/08/22 12:05:41 gammu-smsd[112]: Starting phone communication...
Thu 2024/08/22 12:05:41 gammu-smsd[112]: Error at init connection: Error opening device, you don't have the required permission. (DEVICENOPERMISSION[6])

My HA:
Core 2024.8.2
Supervisor 2024.08.0
Operating System 13.1 
How to solve this?

**Comment by infrat** [comment]
Fixed in https://github.com/infrat/mqtt2sms-addon/commit/b8b541f29b3e31f9cd8bb86a95e5f48f8ff405ab
